#!/usr/bin/env python3
"""issuesmith gen-live — shell step の trampoline テンプレを本体から生成する（#2595 / #2596 / #2828）.

workflows/issuesmith.yml の shell ステップが参照する `<step>-live.md` は、
本体 `<step>.md` が参照する全テンプレ変数を `key=${key}` で
`python3 -m issuesmith dispatch` に渡すだけの trampoline。本体を編集したら本コマンドを
再実行して同期する（tests/test_live_dispatch_sync.py が同期ずれを検出する）。

Usage:
    python3 -m issuesmith gen-live [--check]
        --check: 生成結果と既存ファイルを比較し、差分があれば exit 1（書き込まない）
"""

from __future__ import annotations

import string
import sys

from issuesmith.config import get_config

_cfg = get_config()
REPO_ROOT = _cfg.root
TEMPLATE_DIR = _cfg.paths.template_dir
WORKFLOW_YML = _cfg.paths.workflow
LIVE_SUFFIX = "-live"

_HEADER = """#!/usr/bin/env bash
# AUTO-GENERATED by python3 -m issuesmith gen-live — 手で編集しない。
# ライブ再レンダ trampoline（#2595 / #2596）: この order は enqueue 時に凍結されるが、
# 本体 {step}.md は python3 -m issuesmith dispatch が実行時に再読込・再展開する。
# これにより dispatch 本体・LLM テンプレ・scripts の契約 skew が起きない。
set -euo pipefail
exec python3 -m issuesmith dispatch {step}"""


def shell_steps() -> list[str]:
    """issuesmith.yml から engine: shell のステップ template 名（-live を除いた本体名）を返す。"""
    import yaml

    data = yaml.safe_load(WORKFLOW_YML.read_text(encoding="utf-8"))
    steps: set[str] = set()
    for handler in (data.get("handlers") or {}).values():
        for step in (handler or {}).get("steps") or []:
            if step.get("engine") == "shell":
                name = str(step["template"])
                if name.endswith(LIVE_SUFFIX):
                    name = name[: -len(LIVE_SUFFIX)]
                steps.add(name)
    return sorted(steps)


def body_identifiers(step: str) -> list[str]:
    text = (TEMPLATE_DIR / f"{step}.md").read_text(encoding="utf-8")
    return sorted(set(string.Template(text).get_identifiers()))


def generate(step: str) -> str:
    lines = [_HEADER.format(step=step)]
    for ident in body_identifiers(step):
        lines[-1] += " \\"
        lines.append(f'  "{ident}=${{{ident}}}"')
    return "\n".join(lines) + "\n"


def main(argv: list[str]) -> int:
    check = "--check" in argv
    drift: list[str] = []
    for step in shell_steps():
        out = TEMPLATE_DIR / f"{step}{LIVE_SUFFIX}.md"
        content = generate(step)
        current = out.read_text(encoding="utf-8") if out.exists() else None
        if current == content:
            continue
        if check:
            drift.append(str(out))
        else:
            out.write_text(content, encoding="utf-8")
            print(f"wrote {out.relative_to(REPO_ROOT)}")
    if drift:
        print("trampoline が本体と同期していません。python3 -m issuesmith gen-live を実行してください:")
        for d in drift:
            print(f"  {d}")
        return 1
    return 0


if __name__ == "__main__":
    sys.exit(main(sys.argv[1:]))
