#!/usr/bin/env python3
"""issuesmith gen-live — generate shell step trampoline templates from their bodies (#2595 / #2596 / #2828).

The `<step>-live.md` referenced by shell steps in workflows/issuesmith.yml is a
trampoline that only passes every template variable referenced by the body
`<step>.md` to `python3 -m issuesmith dispatch` as `key=${key}`. Re-run this
command after editing a body to resync (tests/test_live_dispatch_sync.py detects drift).

Usage:
    python3 -m issuesmith gen-live [--check]
        --check: compare the generated output with existing files; exit 1 on any diff (no writes)
"""

from __future__ import annotations

import string
import sys

from issuesmith.config import get_config
from issuesmith.template_ids import template_identifiers

_cfg = get_config()
REPO_ROOT = _cfg.root
TEMPLATE_DIR = _cfg.paths.template_dir
WORKFLOW_YML = _cfg.paths.workflow
LIVE_SUFFIX = "-live"

_HEADER = """#!/usr/bin/env bash
# AUTO-GENERATED by python3 -m issuesmith gen-live — do not edit by hand.
# Live re-render trampoline (#2595 / #2596): this order is frozen at enqueue time,
# but python3 -m issuesmith dispatch re-reads and re-renders the body {step}.md at run time,
# so the dispatch body, LLM templates and scripts never skew on their contracts.
set -euo pipefail
exec python3 -m issuesmith dispatch {step}"""


def shell_steps() -> list[str]:
    """Return template names of engine: shell steps in issuesmith.yml (body names without -live)."""
    import yaml

    data = yaml.safe_load(WORKFLOW_YML.read_text(encoding="utf-8"))
    steps: set[str] = set()
    for handler in (data.get("handlers") or {}).values():
        for step in (handler or {}).get("steps") or []:
            if step.get("engine") == "shell":
                name = str(step["template"])
                if name.endswith(LIVE_SUFFIX):
                    name = name[: -len(LIVE_SUFFIX)]
                steps.add(name)
    return sorted(steps)


def body_identifiers(step: str) -> list[str]:
    text = (TEMPLATE_DIR / f"{step}.md").read_text(encoding="utf-8")
    return sorted(set(template_identifiers(string.Template(text))))


def generate(step: str) -> str:
    lines = [_HEADER.format(step=step)]
    for ident in body_identifiers(step):
        lines[-1] += " \\"
        lines.append(f'  "{ident}=${{{ident}}}"')
    return "\n".join(lines) + "\n"


def main(argv: list[str]) -> int:
    check = "--check" in argv
    drift: list[str] = []
    for step in shell_steps():
        out = TEMPLATE_DIR / f"{step}{LIVE_SUFFIX}.md"
        content = generate(step)
        current = out.read_text(encoding="utf-8") if out.exists() else None
        if current == content:
            continue
        if check:
            drift.append(str(out))
        else:
            out.write_text(content, encoding="utf-8")
            print(f"wrote {out.relative_to(REPO_ROOT)}")
    if drift:
        print("trampolines are out of sync with their bodies; run python3 -m issuesmith gen-live:")
        for d in drift:
            print(f"  {d}")
        return 1
    return 0


if __name__ == "__main__":
    sys.exit(main(sys.argv[1:]))
