"""Pipeline comment filter for issuesmith.

Provides patterns and helpers to distinguish pipeline-generated comments
from user comments when extracting constraints in B1/CP1 templates.
"""

import re

PIPELINE_COMMENT_PATTERNS = [
    "PIPELINE_STATUS:",
    "## B1 ",
    "## CP1 ",
    "## CP2 ",
    "## P3 ",
    "## M1 ",
    "<!-- pipeline-branch:",
]


def is_pipeline_comment(comment_body: str) -> bool:
    """Return True if the comment was generated by the pipeline (not a user)."""
    return any(p in comment_body for p in PIPELINE_COMMENT_PATTERNS)


def extract_user_comments(comments: list[dict]) -> list[dict]:
    """Filter out pipeline-generated comments, returning only user comments."""
    return [c for c in comments if not is_pipeline_comment(c["body"])]


_B1_DEP_HEADER = "## B1 事前検証失敗:"
_UNMERGED_LINE = "未マージ:"
_ISSUE_REF_RE = re.compile(r"#\d+")


def main() -> None:
    """stdin の {body, comments: [...]} JSON からパイプライン自動生成コメントを除去して出力する。

    B1 等のプロンプトが LLM にコメントを読ませる前段で決定論的にフィルタするための CLI。
    """
    import json
    import sys

    data = json.load(sys.stdin)
    comments = data.get("comments") or []
    data["comments"] = extract_user_comments(comments)
    json.dump(data, sys.stdout, ensure_ascii=False, indent=2)
    sys.stdout.write("\n")


def validate_b1_dep_comment(comment_body: str) -> list[str]:
    """Validate B1 dependency-check comment against the §0.5 template.

    Returns a list of violation messages (empty when valid).
    """
    violations: list[str] = []

    if _B1_DEP_HEADER not in comment_body:
        violations.append(f"missing header: {_B1_DEP_HEADER}")

    unmerged_lines = [
        line for line in comment_body.splitlines() if line.strip().startswith(_UNMERGED_LINE)
    ]
    if not unmerged_lines:
        violations.append(f"missing line: {_UNMERGED_LINE}")
    elif not any(_ISSUE_REF_RE.search(line) for line in unmerged_lines):
        violations.append(f"{_UNMERGED_LINE} must contain at least one #<number>")

    if "PIPELINE_STATUS:" not in comment_body:
        violations.append("missing PIPELINE_STATUS: line")

    return violations


if __name__ == "__main__":
    main()
